### ISSUE TITLE
IMDB: TV-shows are identified as movies

### ISSUE THREAD

**Issue by cowcreamer** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#104]
Every TV-show on IMDB is identified as a movie (Radarr icon, redirect to Radarr on click) and can't be added to Sonarr.
Movies work fine.
Version: 2.4.2

![image](https://user-images.githubusercontent.com/106419821/170810207-2fea867b-268d-4b5e-af13-0ad488ba2440.png)

**Comment by cowcreamer** [comment]
Tbh I hadn't even noticed I was using it in German. 
My default language is English but I bought a new laptop and I guess language settings got mixed up in the initial setup.
So, easy fix for me (switch back to my English default) and it will be resolved in a future update. 

Thanks!

**Comment by trossr32** [comment]
Fixed in v2.5.0
