### ISSUE TITLE
IMDB Polls and Lists - Indended to Work with Extension?

### ISSUE THREAD

**Issue by ekk88d** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#107]
The Radarr icon shows on IMDB polls, so I was hoping that the Autosearch extension could add IMDB polls and lists to Radarr, but Radarr-friendly formatting doesn't appear to pass through to the program.

I won't post screenshots, because it is reproduced by clicking the ![image](https://user-images.githubusercontent.com/56038654/172658599-52548fb8-7a33-44ee-b927-ef1a707312a0.png) on an IMDB:
1. Poll page:  https://www.imdb.com/poll/b1vGfx3wZ2g
2. Poll Results page:  https://www.imdb.com/poll/b1vGfx3wZ2g/results or
3. List page:  https://www.imdb.com/list/ls092677596/

Just in case there was surprise functionality added to Radarr, I tried manually adding an IMDB List ID via Radarr's Add New page:

![image](https://user-images.githubusercontent.com/56038654/172659418-a90350b0-d837-41ac-af6a-14d0517dc052.png)

No luck, so maybe Radarr devs are saving that functionality for a rainy day.

In the meantime, Radarr only allows adding IMDB Lists through its Settings>Lists screen, so I'd just recommend the Autosearch extension exempts IMDB List and Poll URLs - imdb.com/list/* and imdb.com/poll/*

@trossr32 Thanks for your ongoing development, especially considering that your extension stays adapted to IMDB & Radarr changes. I use it daily.

For posterity's sake:
Windows 10 v10.0.19044
Chrome v102.0.5005.63 (64-bit)
Radarr v4.1.0.6175 (develop)

**Comment by trossr32** [comment]
Thanks for highlighting; I'd never noticed this. I'll definitely look to exclude polls, but not as a matter of urgency.

**Comment by trossr32** [comment]
I've just looked at this and it doesn't appear to be an issue anymore. Let me know if I'm missing something
