### ISSUE TITLE
Paypal takes over $3 when wanting to send tip

### ISSUE THREAD

**Issue by alheureux88** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#11]
Hello Rob,
I was about to send you a small tip as a token of my appreciation but Paypal want to charge me 3$ on a 5$ tip. I don't think a lot of people will use send paypal to send any tip with that fee. Any other way to support you?

**Comment by trossr32** [comment]
Hi,

First off thank you for the thought, it's incredibly kind of you. I had no
idea PayPal did that so will take a look and try to find a more suitable
implementation.

A great way to support would be to just let me know if you find any issues
with the extension, or to share any ideas you have for improvement if you
think of anything.

Glad you're enjoying it 👍

Rob

**Comment by alheureux88** [comment]
The only feature that would be great is to use the imdb/tvdb ID to skip the search in radarr/sonarr. Otherwise, I can't think of anything else. I already left a review on both of your extension for firefox!

**Comment by trossr32** [comment]
Good idea; I was considering implementing an integration with the Sonarr/Radarr APIs to change the icons displayed on IMDb, etc. and mark them with a tick or similar if the movie/tv show already exists in Sonarr/Radarr. Might be possible to do some direct integration with IMDB/TVDb ids too.
