### ISSUE TITLE
Lidarr failing test

### ISSUE THREAD

**Issue by Simpuhl** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#111]
All details are correct for Lidarr enable, but tests are failing with the general failed message:

Failed, please double check the domain and API key

Sonarr & Radarr working fine.
![2022-06-26 17_30_50-Sonarr_Radarr_Lidarr autosearch options and 3 more pages - Personal - Microsoft​](https://user-images.githubusercontent.com/262571/175840365-07c3f329-0c10-48b5-8480-61ea9cd5f52b.png)

**Comment by ash0080** [comment]
same

**Comment by trossr32** [comment]
It appears the Lidarr API has been updated and no longer provides a version endpoint: https://lidarr.audio/docs/api/#/

Worse, I can no longer get a response from the API other than a 406. 

To that end, I'm going to leave this issue open and hopefully will be able to fix following a subsequent update of Lidarr.

In the interim, I'm afraid anyone wishing to use Lidarr will need to uncheck the _auto populate from API_ switch in the advanced settings tab and configure _search path URL_ and _search field selector_ themselves (assuming the default values don't work correctly; they should I believe).

**Comment by Simpuhl** [comment]
I will test the temporary work around and get back to you. Thank you

**Comment by trossr32** [comment]
Not to self: retest this and add a note to the UI if auto-population is still not working

**Comment by hugalafutro** [comment]
Just wanted to say auto populate still doesn't work with latest Lidarr as of writing this, I think adding the note to the UI would be good as I just spent good chunk of time messing with settings until I found this issue.

**Comment by trossr32** [comment]
I have a PR to review this weekend and will hopefully find enough time to do some dev work too, so will look into this again

**Comment by trossr32** [comment]
Should be fixed
