### ISSUE TITLE
Support for Prowlarr

### ISSUE THREAD

**Issue by githubbapoopa** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#118]
If I understand correctly what terrific job you did here, then support for Readarr, Whisparr and foremost Prowlarr should be possible.

Prowlarr support would really be fantastic.

**Comment by trossr32** [comment]
**Prowlarr support**

Prowlarr doesn't have the same format of search functionality as the servarr implementations (from a UI perspective) and so currently won't be implemented. I'm using Prowarr in my own setup now so will watch for a version update to see if anything cane be done later. Additionally, The only use case I can see for the extension is to add Prowlarr as an option to the context menu for highlight searching, as it doesn't make sense for it to be part of any of the external site integrations (in my opinion, happy to hear more ideas for implementation)

**Whisparr support**

I don't use this and I'm not really interested in putting the work in to support it. If anyone really wants this they're welcome to do the work themselves on a fork. I would accept a working PR to include in the extension, but again I'm not going to support if it breaks down the line.

**Readarr support**

I've just played around with setting up Readarr, and it seems the recommended approach is to have 2 instances; one for ebooks and the other for audiobooks (at least this is how I set up my server). Like with Prowlarr, I'm not sure whether site integrations will be possible or useful. I can investigate adding to the context menu.

Apologies for any development delays; I'm currently working full time and have a side contract so I don't have much spare development time at the moment. Hopefully I'll be able to do the Readarr work soon. Going to close this ticket as Readarr is covered in #91

**Comment by githubbapoopa** [comment]
Pity but not your fault.

Thanks for your effort.

Currently I'm playing around with https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu

Maybe there's a solution to somehow do a Firefox context search in Prowlarr.

Thx

**Comment by trossr32** [comment]
If you get anywhere with it please let me know 👍
