### ISSUE TITLE
Add TVMaze as a source

### ISSUE THREAD

**Issue by Mantene** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#13]
It would be great to be able to add a TV show while browsing TVMaze - especially their Countdown section.

**Comment by trossr32** [comment]
Thanks, I'll take a look at implementing this for you 👍 

_Note to self_ - consider making the implementations functionality generic and configurable for users.

**Comment by trossr32** [comment]
TVmaze integration added in v1.2.0, currently being reviewed in all stores.

**Comment by Mantene** [comment]
It works beautifully! Thank you!
