### ISSUE TITLE
Radarr/Sonarr not auto-seaching once opened

### ISSUE THREAD

**Issue by KillerKelvUK** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#133]
The settings test return success, site integrations appear working, I click say on the radarr icon shown on an IMDB page and my radarr app opens at the search page but is waiting for my input.  I can see the URL includes the movie named linked from the IMDB page however.  Have I missed a configuration step?  Thanks.

**Comment by trossr32** [comment]
Auto-searching is definitely working fine for me with imdb and radarr v4.5.2.7318.

Tested using: https://www.imdb.com/title/tt0096895

The auto-search functionality works using the search field selector in the advanced settings tab, which should be correct when set to 'Auto populate from API'.

Can you provide:

- your radarr version
- the imdb link you are using
- a screenshot of your advanced settings tab of the extension (I just need to see the _Search field selector_ value for radarr)

**Comment by KillerKelvUK** [comment]
Hi thanks for the confirmation, for reference I'm running radarr in a docker image using the linuxserver.io latest version which is 4.4.4.7068.  I've just retested and its now working, not sure what happened previously happy to call it user error but I've not done anything different so that or by the grace of your intervention :-)

**Comment by trossr32** [comment]
Glad it's sorted for you 👍
