### ISSUE TITLE
Icon not showing on IMDB

### ISSUE THREAD

**Issue by jakanaka** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#134]
https://www.imdb.com/title/tt2494376/

I think this happens when a content is labeled as video on IMDB

**Comment by jakanaka** [comment]
https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/blob/965144bfb80f9dbb58808a0d4f6912345783489a/src/content/js/content_script.js#L55

**Comment by trossr32** [comment]
I agree that both icons should show; hopefully this is enough of an edge case that further issues won't be raised because 2 icons are showing. This will go up in the next release.
