### ISSUE TITLE
Limit extension permissions to sites used only

### ISSUE THREAD

**Issue by duderin0** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#145]
Hi there, on the Firefox extension page ([here](https://addons.mozilla.org/en-US/firefox/addon/sonarr-radarr-lidarr-search/)) under the permissions section, it states the extension needs "Access your data for all websites". Since the extension is only used with a limited number of websites, is there a way the scope could be changed to just those? I've seen other extensions do this, [here](https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-test/) is one example. 

Though if there's some other reason its needed though and can't be changed, maybe for the Sonarr/Radarr integration, this issue can just be closed. Thanks for the work, the extension is pretty handy!

**Comment by trossr32** [comment]
Good idea, will implement in the next release

**Comment by trossr32** [comment]
Released in v2.8.0

**Comment by trossr32** [comment]
FYI This change is being reverted in v2.8.1. All URLs permission is required because the extension performs the automated search on servarr instances, and this has broken since the release of v2.8.0.

There's no way to know what the URL of anyone's servarr instance would be, so URL limiting is just not possible.

**Comment by 0xdevalias** [comment]
> I'm not sure about in Firefox/etc, but within Chrome, would the `chrome.permissions` API allow for this?
> 
> - https://developer.chrome.com/docs/extensions/reference/api/permissions
>   - > Use the chrome.permissions API to request [declared optional permissions](https://developer.chrome.com/docs/extensions/develop/concepts/declare-permissions) at run time rather than install time, so users understand why the permissions are needed and grant only those that are necessary.
> 
> This part specifically looks relevant, and makes me think it should be possible:
> 
> If you want to request hosts that you only discover at runtime, include `"https://*/*"` in your extension's `optional_host_permissions` field. This lets you specify any origin in [`"Permissions.origins"`](https://developer.chrome.com/docs/extensions/reference/api/permissions#property-Permissions-origins) as long as it has a matching scheme. 
>
> _Originally posted by @0xdevalias in [#241](https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/issues/241#issuecomment-2638503812)_
