### ISSUE TITLE
Trakt import issue

### ISSUE THREAD

**Issue by taffo73** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#158]
issue is with the import button as per shot there are two radarr ones the one on the left opens raddarr but doesn't fill the tmdb but when I click the smaller one on the right it fills it as it should! when you hover over the icons you can see that the alt text doesn't add the tmdb number on the left one but does on the other
<img width="305" alt="image" src="https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/assets/49888735/e04c9058-61c6-4fbd-9650-eb2b03dcd28c">

**Comment by trossr32** [comment]
Issue only appears on Edge and only when logged in to Trakt; investigating fix

**Comment by trossr32** [comment]
Fix will go out with v2.8.3
