### ISSUE TITLE
Not working with Arc browser

### ISSUE THREAD

**Issue by almottier** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#166]
Hello,

I configured Radarr/Sonarr in the extension in the [Arc browser](https://arc.net/) on MacOS (based on Chromium). 
When I open the link from IMDB for example, it doesn't autofill the search bar with the movie name in Radarr.

**Comment by trossr32** [comment]
@almottier Sorry, I can't help with this one as I don't own a Mac

**Comment by almottier** [comment]
Hello,

Arc browser is now available [on Windows](https://arc.net/download). Is anyone able to reproduce the issue on this platform?

**Comment by trossr32** [comment]
@almottier I've installed the Arc browser on Windows and have successfully tested my Radarr searches when I click the icon injected on this IMDb page: https://www.imdb.com/title/tt6263850/

I have just released a new version of the extension to use manifest v3 (for the Chrome version, which is the one used in Arc). I don't know if this has helped fix an issue.

**Comment by almottier** [comment]
Hello @trossr32 , it's working for me now and it should have been working with Arc all along... indeed I was using http instead of https in the settings. The "Test" was passing fine but the input box remained empty... Thanks and sorry 👍
