### ISSUE TITLE
[BUG] Integration on episode list for show

### ISSUE THREAD

**Issue by arogl** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#176]
While browsing here [Philharmonia](https://www.imdb.com/title/tt7707100/), I clinked on the the [episode guide](https://www.imdb.com/title/tt7707100/episodes/), which then created the following link `http://localhost:8989/add/new/Episode%20list`

Running version 2.8.4.0 of the chrome extension

Chrome Version 120.0.6099.217 (Official Build) (64-bit)

**Comment by trossr32** [comment]
Fixed with v2.8.5
