### ISSUE TITLE
[Firefox] Can't login to sony.com with add-on enabled

### ISSUE THREAD

**Issue by glottisfaun0000** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#181]
I was getting a "something went wrong" error from the login page for Sony/Playstation store and figured out through process of elimination that this was the add-on in my Firefox install that was causing it.

Steps to reproduce:
1. Go to https://www.playstation.com/en-us/ with add-on enabled in Firefox
2. Click "Sign in"
3. Go to email field
4. Page should switch to a "something went wrong" error

Firefox 122.0.1

**Comment by trossr32** [comment]
Is this still happening? Just tried with (Firefox 123.0) and I can't reproduce.

**Comment by trossr32** [comment]
Closing as unable to reproduce and no response for 6 months
