### ISSUE TITLE
Feature request: letterboxd integration

### ISSUE THREAD

**Issue by aommm** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#30]
Hi,

First and foremost, thanks for making this addon!
I was looking for an easy way to add Radarr integration directly to IMDB, and this fits the bill very nicely. 😄 
(I was originally looking at [web-to-plex](https://github.com/SpaceK33z/web-to-plex) which seems more fully featured, but it looks to be slightly abandoned)

**Feature request**
Support for letterboxd.com. Example link to a film: https://letterboxd.com/film/abelard-die-entmannung/

I started working on a PR for this now, will update here in the coming days

**Comment by trossr32** [comment]
Submitted for review in all web extension stores as v1.5.0.0
