### ISSUE TITLE
support for IMDb's updated Title page

### ISSUE THREAD

**Issue by rayures** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#32]
imdb is updating the Title page. 

https://help.imdb.com/article/issues/GMWASETVPLJYXEZE

**Comment by trossr32** [comment]
@rayures thanks for raising, I'll look at catering for this change ASAP

**Comment by trossr32** [comment]
Submitted for review in all web extension stores as v1.6.0.0

**Comment by rayures** [comment]
wow, that was quick  :-) 

tested on Kubuntu 20.04, Firefox 84.0.2 (64-bit). Imdb old and new works. 

tnx!
