### ISSUE TITLE
Plex support

### ISSUE THREAD

**Issue by aommm** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#36]
Hi,

It would be nice with [Plex](https://www.plex.tv/) support in addition to sonarr/radarr/lidarr.

To start with, an MVP could just be a direct link to Plex search.

Then I can imagine some cool things down the road, if we use the Plex API:
- Show availability of movie on Plex
- "Watch now" link

I'd be willing to contribute to this eventually, but I'll prio #35. Curious to hear your thoughts!

**Comment by trossr32** [comment]
Happy to talk about this, but I'll leave to one side for now and take a look at #35 👍

**Comment by nigeljorda** [comment]
Please add this but without all the hassle, just a icon to open the movie on Plex web in radarr and for show on radarr. This can even be done with only searching the title of the show/movie
