### ISSUE TITLE
Test Firefox polyfilling to remove the need for a separate chrome extension code base.

### ISSUE THREAD

**Issue by trossr32** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#43]
https://extensionworkshop.com/documentation/develop/browser-compatibility/
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
https://github.com/mozilla/webextension-polyfill

**Comment by trossr32** [comment]
@aommm created this issue following on from my comment in pull request #39

**Comment by aommm** [comment]
FYI @trossr32 I'm taking a stab at this now!

**Comment by trossr32** [comment]
Released with v2 which will roll out to all browsers once approved.
