### ISSUE TITLE
TV Calendar integration

### ISSUE THREAD

**Issue by poohbah** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#46]
The [TV Calendar](https://www.pogdesign.co.uk/cat/) website is absolutely fantastic for discovering new TV show launches. I generally go there, find series premieres (highlighted yellow), then google search the title or use the right click integration on the title to search via sonarr. It would be great if you could add the integration directly on the site.

**Comment by ekk88d** [comment]
I would also love to see this integration. Thanks for raising it

**Comment by trossr32** [comment]
Released with v2 which will roll out to all browsers once approved, please let me know if there are any issues.
