### ISSUE TITLE
Integrations not appearing on background-loaded tabs until manual refresh

### ISSUE THREAD

**Issue by trrrey** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#58]
Using current version of Edge on Windows 10.  
Tried on Trakt and IMDB and both required a refresh (F5) of the page to get the integration to appear.  Tried a few movies and shows (just randomly from links on the first page).
Happens both with Sonarr and Radarr integration candidates.
Restarted browser and tried again with same problem.

(Also, related: While testing, one time I had the tabs open for awhile and returned to the tabs to see both IMDB and Trakt had 2 integration buttons instead of 1.  This only happened once, but I just discovered and installed the extension today)

**Comment by trrrey** [comment]
I figured out the "2 buttons appearing" happens when you click on the sonarr/radarr integration and then go back to the imdb/trakt tab.

**Comment by trossr32** [comment]
This is a known issue and I believe it's due to the browser not allowing extensions to run in background tabs (i.e. spawning a new tab without it being active). I looked into this a couple of years ago so it may now be possible. Will investigate.

**Comment by trossr32** [comment]
Both issues fixed in version 2.1. 

Technically the extension doesn't run when a background tab is spawned, but the extension is now run as soon as a tab is made active (clicked) which removes the need for a manual refresh.
