### ISSUE TITLE
Edge store version not updating with new release 2.1

### ISSUE THREAD

**Issue by trrrey** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#62]
Was waiting for the extension to update for Edge but it hasn't, while the Chrome and Firefox stores were updated right away.

Not a big deal, but didn't want to have to uninstall / reinstall /configure by switching stores.

**Comment by trossr32** [comment]
@trrrey Microsoft takes about a week to review version updates, Chrome takes about 24 hours and Firefox is usually instant. Just have to be patient I'm afraid.

I know the version number is updated in the README but Edge doesn't allow auto version population of those badges like the other browsers, so I have to update that manually.

**Comment by trossr32** [comment]
@trrrey Had an email from Microsoft to say the new version is up 👍

**Comment by trrrey** [comment]
great, thanks for the update!
