### ISSUE TITLE
Feature Request: Last.FM integration

### ISSUE THREAD

**Issue by DeftNerd** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#72]
I already have my Lidarr set to scrobble to Last.FM. Now the website generates a nice list of artists that it thinks that I might enjoy. 

This extension would be super useful to browse the site and quickly add artists to Lidarr for monitoring and downloading.

**Comment by trossr32** [comment]
In staging, will go up with release 2.3.0
