### ISSUE TITLE
On Simkl the icon Z index change to z-index: 1

### ISSUE THREAD

**Issue by masyk** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#73]
Simkl icon Z index change to z-index: 1 from z-index: 100 as it floats on top of the logo at 100.
![image](https://user-images.githubusercontent.com/9755957/143299006-e8e13217-d7ee-485f-8747-5b3ddc7496f1.png)

**Comment by trossr32** [comment]
In staging, will go up with release 2.3.0
