### ISSUE TITLE
When I have the extension installed the word "new" keeps being added to the search box whenever I load the search page on Sonarr/Radarr

### ISSUE THREAD

**Issue by alexander-paterson** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#74]

**Comment by hooligeek** [comment]
I've noticed similar behavior when searching from the top search bar.

![image](https://user-images.githubusercontent.com/59208486/146605670-fbdd3d91-4c20-488e-b1c7-1b9ff2d10ffb.png)


but when I use the larger search bar below it works fine.

![image](https://user-images.githubusercontent.com/59208486/146605829-c24cc3e4-0378-4d7f-b8bc-b3d68ed36fc3.png)

**Comment by trossr32** [comment]
In staging, will go up with release 2.3.0
