### ISSUE TITLE
Unlimited Lidarr Icons on Musicbrainz

### ISSUE THREAD

**Issue by lostandlost** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#78]
Firefox 95.0.1
Add-on 2.2.0.0
Lidarr 1.0.0.2378

Whenever I select a different tab, then go back to the Musicbrainz tab a new Lidarr search icon is added.  It also seems to add more search terms in the new Lidarr icon.  The example link below is after leaving and coming back to the Musicbrainz tab a handful of times.  I did redact my port number, so no need to worry about that.  :)

`http://localhost:XXXX/lidarr/add/search/http%3A%2F%2Flocalhost%3AXXXX%2Flidarr%2Fadd%2Fsearch%2Fhttp%253a%252f%252flocalhost%253aXXXX%252flidarr%252fadd%252fsearch%252fhttp%25253a%25252f%25252flocalhost%25253aXXXX%25252flidarr%25252fadd%25252fsearch%25252fhttp%2525253a%2525252f%2525252flocalhost%2525253aXXXX%2525252flidarr%2525252fadd%2525252fsearch%2525252fhttp%252525253a%252525252f%252525252flocalhost%252525253aXXXX%252525252flidarr%252525252fadd%252525252fsearch%252525252fhttp%25252525253a%25252525252f%25252525252flocalhost%25252525253aXXXX%25252525252flidarr%25252525252fadd%25252525252fsearch%25252525252fhttp%2525252525253a%2525252525252f%2525252525252flocalhost%2525252525253aXXXX%2525252525252flidarr%2525252525252fadd%2525252525252fsearch%2525252525252fhttp%252525252525253a%252525252525252f%252525252525252flocalhost%252525252525253aXXXX%252525252525252flidarr%252525252525252fadd%252525252525252fsearch%252525252525252fhttp%25252525252525253a%25252525252525252f%25252525252525252flocalhost%25252525252525253aXXXX%25252525252525252flidarr%25252525252525252fadd%25252525252525252fsearch%25252525252525252fhttp%2525252525252525253a%2525252525252525252f%2525252525252525252flocalhost%2525252525252525253aXXXX%2525252525252525252flidarr%2525252525252525252fadd%2525252525252525252fsearch%2525252525252525252fhttp%252525252525252525253a%252525252525252525252f%252525252525252525252flocalhost%252525252525252525253aXXXX%252525252525252525252flidarr%252525252525252525252fadd%252525252525252525252fsearch%252525252525252525252fhttp%25252525252525252525253a%25252525252525252525252f%25252525252525252525252flocalhost%25252525252525252525253aXXXX%25252525252525252525252flidarr%25252525252525252525252fadd%25252525252525252525252fsearch%25252525252525252525252fhttp%2525252525252525252525253a%2525252525252525252525252f%2525252525252525252525252flocalhost%2525252525252525252525253aXXXX%2525252525252525252525252flidarr%2525252525252525252525252fadd%2525252525252525252525252fsearch%2525252525252525252525252fhttp%252525252525252525252525253a%252525252525252525252525252f%252525252525252525252525252flocalhost%252525252525252525252525253aXXXX%252525252525252525252525252flidarr%252525252525252525252525252fadd%252525252525252525252525252fsearch%252525252525252525252525252fhttp%25252525252525252525252525253a%25252525252525252525252525252f%25252525252525252525252525252flocalhost%25252525252525252525252525253aXXXX%25252525252525252525252525252flidarr%25252525252525252525252525252fadd%25252525252525252525252525252fsearch%25252525252525252525252525252fhttp%2525252525252525252525252525253a%2525252525252525252525252525252f%2525252525252525252525252525252flocalhost%2525252525252525252525252525253aXXXX%2525252525252525252525252525252flidarr%2525252525252525252525252525252fadd%2525252525252525252525252525252fsearch%2525252525252525252525252525252fhttp%252525252525252525252525252525253a%252525252525252525252525252525252f%252525252525252525252525252525252flocalhost%252525252525252525252525252525253aXXXX%252525252525252525252525252525252flidarr%252525252525252525252525252525252fadd%252525252525252525252525252525252fsearch%252525252525252525252525252525252fhttp%25252525252525252525252525252525253a%25252525252525252525252525252525252f%25252525252525252525252525252525252flocalhost%25252525252525252525252525252525253aXXXX%25252525252525252525252525252525252flidarr%25252525252525252525252525252525252fadd%25252525252525252525252525252525252fsearch%25252525252525252525252525252525252fhttp%2525252525252525252525252525252525253a%2525252525252525252525252525252525252f%2525252525252525252525252525252525252flocalhost%2525252525252525252525252525252525253aXXXX%2525252525252525252525252525252525252flidarr%2525252525252525252525252525252525252fadd%2525252525252525252525252525252525252fsearch%2525252525252525252525252525252525252fhttp%252525252525252525252525252525252525253a%252525252525252525252525252525252525252f%252525252525252525252525252525252525252flocalhost%252525252525252525252525252525252525253aXXXX%252525252525252525252525252525252525252flidarr%252525252525252525252525252525252525252fadd%252525252525252525252525252525252525252fsearch%252525252525252525252525252525252525252fhttp%25252525252525252525252525252525252525253a%25252525252525252525252525252525252525252f%25252525252525252525252525252525252525252flocalhost%25252525252525252525252525252525252525253aXXXX%25252525252525252525252525252525252525252flidarr%25252525252525252525252525252525252525252fadd%25252525252525252525252525252525252525252fsearch%25252525252525252525252525252525252525252fhttp%2525252525252525252525252525252525252525253a%2525252525252525252525252525252525252525252f%2525252525252525252525252525252525252525252flocalhost%2525252525252525252525252525252525252525253aXXXX%2525252525252525252525252525252525252525252flidarr%2525252525252525252525252525252525252525252fadd%2525252525252525252525252525252525252525252fsearch%2525252525252525252525252525252525252525252fhttp%252525252525252525252525252525252525252525253a%252525252525252525252525252525252525252525252f%252525252525252525252525252525252525252525252flocalhost%252525252525252525252525252525252525252525253aXXXX%252525252525252525252525252525252525252525252flidarr%252525252525252525252525252525252525252525252fadd%252525252525252525252525252525252525252525252fsearch%252525252525252525252525252525252525252525252flidarr%25252525252525252525252525252525252525252525253a20ff3303-4fe2-4a47-a1b6-291e26aa3438`

**Comment by trossr32** [comment]
Thanks for raising, I'll take a look

**Comment by trossr32** [comment]
Fixed and released as version 2.3.1

**Comment by KnifeFed** [comment]
I have the same issue with Radarr icons on IMDb. If I'm on a movie page, scroll down a bit, switch to another tab, switch back and scroll up, there's an extra Radarr icon.

**Comment by lostandlost** [comment]
> I have the same issue with Radarr icons on IMDb. If I'm on a movie page, scroll down a bit, switch to another tab, switch back and scroll up, there's an extra Radarr icon.

I too am seeing this issue on add-on version 2.4.0.0 in Firefox 96.0.3. 

![image](https://user-images.githubusercontent.com/3107789/152691358-ca3b675f-4549-444d-8251-9ac556ab2084.png)
