### ISSUE TITLE
Lidarr - no context menu

### ISSUE THREAD

**Issue by Markyb0y** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#86]
have just installed the extension and context menu working fine for Sonarr and Radarr, but no context menu appears on right click for Lidarr.

if I search last.fm for an artist the lidarr icon appears and works correctly, its just the context menu not having a third line to search highlighted text with Lidarr.

![image](https://user-images.githubusercontent.com/271739/148912474-b58905d1-e6d4-4f3c-b858-1d252d89217b.png)

Chrome Version 97.0.4692.71 (Official Build) (64-bit)

thanks

**Comment by trossr32** [comment]
Issue has been fixed with release 2.4.0.0. Please allow some time for the extension to be updated across the various app stores.
