### ISSUE TITLE
[Feature] If Sonarr/Radarr tab already open use that tab rather than open a new tab

### ISSUE THREAD

**Issue by alexander-paterson** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#92]
I tend to keep Sonarr/Radarr open in tabs, when I use the extension a new tab opens. It would be awesome if the extension could check whether there was an existing tab open and if there is use that instead.

**Comment by trossr32** [comment]
I don't think this is possible as the extension is simply injecting am anchor link on to the host page. I'll do some research on the chance I'm wrong though,

**Comment by trossr32** [comment]
Not going to do this as it would require the extension to have more permissions. The idea is to quickly perform a search, after which the tab can be closed so I don't see this as being important.
