### ISSUE TITLE
IMDB integration stopped working

### ISSUE THREAD

**Issue by dcquence** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#93]
In the last few days integration with IMDB has stopped working. Tested on numerous browsers, all other sites still work fine.

**Comment by Bajnep** [comment]
the selector "TitleHeader__TitleText" doesn't exist any more. since there is only one H1 tag in the whole page, maybe use that as the selector for the icon.

**Comment by trossr32** [comment]
Will try and resolve this week

**Comment by trossr32** [comment]
Fixed in v2.4.1, will be updated across browser stores soon
